services:
  retirement-analysis:
    build: .
    container_name: retirement-analysis
    volumes:
      - ../input:/app/input
      - ./retirement_config.json:/app/retirement_analysis/retirement_config.json
      - ./output:/app/retirement_analysis/output
      - ./temp:/app/retirement_analysis/temp